// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB067b1sG_iqCXdQ5t8dW5zWLYBPWwgGrA',
    appId: '1:847334305425:web:07976e007449b3a0809930',
    messagingSenderId: '847334305425',
    projectId: 'dairyapp-c0504',
    authDomain: 'dairyapp-c0504.firebaseapp.com',
    storageBucket: 'dairyapp-c0504.firebasestorage.app',
    measurementId: 'G-KZK0NE81HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoZTjbTV092O_kLV78UYbrc_M3iFMxy9Q',
    appId: '1:847334305425:android:1702e13f73e3541d809930',
    messagingSenderId: '847334305425',
    projectId: 'dairyapp-c0504',
    storageBucket: 'dairyapp-c0504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgiHt4z3voa83X8weZX5eKHHGJTXJldj0',
    appId: '1:847334305425:ios:99828cefd40d12b5809930',
    messagingSenderId: '847334305425',
    projectId: 'dairyapp-c0504',
    storageBucket: 'dairyapp-c0504.firebasestorage.app',
    iosBundleId: 'com.example.dairyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgiHt4z3voa83X8weZX5eKHHGJTXJldj0',
    appId: '1:847334305425:ios:99828cefd40d12b5809930',
    messagingSenderId: '847334305425',
    projectId: 'dairyapp-c0504',
    storageBucket: 'dairyapp-c0504.firebasestorage.app',
    iosBundleId: 'com.example.dairyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB067b1sG_iqCXdQ5t8dW5zWLYBPWwgGrA',
    appId: '1:847334305425:web:38701dd4790ff977809930',
    messagingSenderId: '847334305425',
    projectId: 'dairyapp-c0504',
    authDomain: 'dairyapp-c0504.firebaseapp.com',
    storageBucket: 'dairyapp-c0504.firebasestorage.app',
    measurementId: 'G-QJK0N0TPW7',
  );

}